name: Example workflow for Maven using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
        - name: Detect secrets with Talisman in incoming commits
          uses: carhartl/talisman-secrets-scan-action@v1.3.0
